# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.ello.oa.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:system/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

spring:
  profiles:
    # 激活yml文件
    active: druid

    #资源信息
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn


# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5

# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间，-1代表永不过期（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
    # 同一个用户最大会话数，比如2的意思是同一个账号允许最多同时两个人登录（默认-1不限制）
    maxSession: -1
    # 踢出之前登录的/之后登录的用户，默认踢出之前登录的用户
    kickoutAfter: false

server:
  port: 8081

dog:
  name: dog
  age: 10

person:
  name: 榴莲${random.int}
  age: 11
  a-boolean: true
  map: {k1: v1,k2: v2}
  list: [1,2,3]
  birth: 2020/01/01


---
spring:
  profiles: dev

server:
  port:8084
---